version: '3'

services:
  server:
    container_name: nq-dashboard
    image: nginx:alpine3.18
    restart: always
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - traefik.enable=true
      - traefik.http.services.nq-dashboard.loadbalancer.server.port=80
      - traefik.http.routers.nq-dashboard.rule=Host("dashboard.innque.com")
      - traefik.http.routers.nq-dashboard.entrypoints=web
      - traefik.http.routers.nq-dashboard_secured.rule=Host("dashboard.innque.com")
      - traefik.http.routers.nq-dashboard_secured.entrypoints=websecure
      - traefik.http.routers.nq-dashboard_secured.tls.certresolver=myhttpchallenge
      - traefik.http.routers.nq-dashboard.middlewares=redirect@file


networks:
  default:
    external:
      name: server-network
